### ISSUE TITLE
Reference-free parser

### ISSUE THREAD

**Issue by asbjornu** [qwertie/ecsharp#27]
Is it possible to use LLLPG to generate a parser that has no external references (i.e. is self-contained)? If not, please consider this a feature request! :smile:

**Comment by qwertie** [comment]
Yes, there is an example of such a parser here:
https://github.com/qwertie/LLLPG-Release/tree/master/CalcExample-Standalone

**Comment by asbjornu** [comment]
Excellent, thanks!

**Comment by qwertie** [comment]
Actually that's not so much "an" example as "THE" example, since the standalone ParserSource and LexerSource are not published anywhere else. Happy parsing!

**Comment by asbjornu** [comment]
:smile: :+1:
