### ISSUE TITLE
replacePP doing mysterious substitution outside of macro scope

### ISSUE THREAD

**Issue by j4m3z0r** [qwertie/ecsharp#60]
Ok, one more issue -- sorry to be finding so many! It's entirely possible this is my misunderstanding, but here's what I found nonetheless.

The following code will, amongst other things, emit these two lines:
```
public CSVar this[CSVar x, CSVar y, CSVar z] => GetExpr(x, y, z);
public CSVar this[CSVar x, CSVar y, CSExpr z] => GetExpr(x, y, z);
```
This is surprising, since neither of the 2 macros that do the work (`Indexer2D` and `Indexer3D`) should emit *anything* that starts with `public CSVar` (they should only emit `public CSExpr`). If you comment out this line:
```
ExecMacro2D(Indexer2D);
```
Then the errant lines disappear (along with all the 2D indexer code). Similarly, if I rename arg1, 2 & 3 to some other name (say, arga, b & c), the the problem goes away.

My understanding was that the replacePP function would be limited to its current scope, but even if it weren't, I can't understand how it would replace the CSExpr return type, since that should be a single, complete token.

Code showing the problem follows:
```
replace(AllTypes => (Var, Expr));

// Execute the given macro with all permutations of types for 3 arguments.
define ExecMacro2D($macro2d) {
    unroll (T1 in AllTypes) {
        unroll(T2 in AllTypes) {
            $macro2d(T1, T2);
        }
    }
}

// Execute the given macro with all permutations of types for 3 arguments.
define ExecMacro3D($macro3d) {
    unroll (T1 in AllTypes) {
        unroll(T2 in AllTypes) {
            unroll(T3 in AllTypes) {
                $macro3d(T1, T2, T3);
            }
        }
    }
}

define Indexer2D($T1, $T2) {
    replacePP(arg1 => concatId(CS, $T1));
    replacePP(arg2 => concatId(CS, $T2));
    public CSExpr this[arg1 x, arg2 y] => GetExpr(x, y);
}
ExecMacro2D(Indexer2D);

define Indexer3D($T1, $T2, $T3) {
    replacePP(arg1 => concatId(CS, $T1));
    replacePP(arg2 => concatId(CS, $T2));
    replacePP(arg3 => concatId(CS, $T3));
    public CSExpr this[arg1 x, arg2 y, arg3 z] => GetExpr(x, y, z);
}
ExecMacro3D(Indexer3D);
```

**Comment by qwertie** [comment]
This is likely to be some sort of bug. A workaround is to use braces with `replace`/`replacePP`:

~~~cs
define Indexer2D($T1, $T2) {
    replacePP(arg1 => concatId(CS, $T1));
    replacePP(arg2 => concatId(CS, $T2)) {
      public CSExpr this[arg1 x, arg2 y] => GetExpr(x, y);
    }
}
~~~

**Comment by qwertie** [comment]
In the future, I would request that you look for a less complex test case... this shows the problem just as well:

~~~
define Indexer2D($T1, $T2) {
    replacePP(arg1 => concatId(CS, $T1));
    replacePP(arg2 => concatId(CS, $T2));
    public CSExpr this[arg1 x, arg2 y] => GetExpr(x, y);
}
unroll (T1 in (Var, Expr)) {
    Indexer2D(T1, Var);
}

define Indexer3D($T1, $T2, $T3) {
    replacePP(arg1 => concatId(CS, $T1));
    replacePP(arg2 => concatId(CS, $T2));
    replacePP(arg3 => concatId(CS, $T3));
    public CSExpr this[arg1 x, arg2 y, arg3 z] => GetExpr(x, y, z);
}
unroll (T1 in (Var, Expr)) {
    Indexer3D(T1, Var, Var);
}
~~~

For quick experimentation, `LeMP.exe --editor` is helpful (if you can [find LeMP on your hard drive](https://www.voidtools.com/))

**Comment by qwertie** [comment]
I was able to further reduce it to this...

~~~csharp
define Indexer2D($T1) {
    replacePP(arg1 => concatId(CS, $T1));
    public CSExpr this[arg1 x, arg2 y] => GetExpr(x, y);
}
Indexer2D(Expr);

define Indexer3D($T1) {
    replacePP(arg1 => concatId(CS, $T1));
    public CSExpr this[arg1 x, arg2 y, arg3 z] => GetExpr(x, y, z);
}
Indexer3D(Var);
~~~

I'd started to suspect that LeMP is actually working as intended... and with simple enough code you can understand why. But first it is necessary to understand that

- The braces in `define` delimit the edges of the macro expansion, but they do not create a scope: When the macro is expanded, the braces disappear.
- Macro execution order is outside-in, so the macro created with `define` is expanded before its children. (More specifically the `define` block itself expands to nothing - it registers a new macro, then deletes itself from the output, and then when you use the defined name (such as `Indexer3D`) the new macro gets expanded at that point. Earlier, you asked me earlier why macros expand outside-in, and this example illustrates a good reason why. `define` itself is a macro, and if `concatId` were processed before `define` then it would produce the nonsensical identifier like `CS$T1`.)
- When `replace/replacePP` are used without braces, they affect all statements at the same level of nesting.

With this in mind you can see that the calls to `Indexer2D` and `Indexer3D` expand to this:

~~~csharp
replacePP(arg1 => concatId(CS, Expr));
public CSExpr this[arg1 x, arg2 y] => GetExpr(x, y);
replacePP(arg1 => concatId(CS, Var));
public CSExpr this[arg1 x, arg2 y, arg3 z] => GetExpr(x, y, z);
~~~

And now you can see that the first `replacePP` unintentionally applied to all the statements below it. In particular, the first `replacePP` changes `replacePP(arg1 => concatId(CS, Var));` to `replacePP(concatId(CS, Expr) => concatId(CS, Var));` which of course means `replacePP(CSExpr => CSVar);` and that's what caused the problem.

So the lesson here - a lesson I am learning myself today - is that you shouldn't use `replace/replacePP` without braces inside `define` unless you are really sure you know what you are doing.

**Comment by j4m3z0r** [comment]
Wow, thanks for the detailed explanation! Apologies for not further reducing my test case; I had reduced it pretty substantially from the original program, but I'll attempt to reduce it further in future.

I'll update my code to use braces and see how it goes.

**Comment by j4m3z0r** [comment]
One quick follow-up to clarify your guidance about using braces for replace / replacePP: my reading of the above is that it should suffice to use braces only for the first replace / replacePP invocation, as that would create a scope that would limit substitutions to the current macro -- is that right?

If not, that's fine; I just end up with some very heavily indented code otherwise :)

**Comment by j4m3z0r** [comment]
Ok, to answer my own question: it seems that my reading was wrong: you do need to use braces for all invocations. So braces do not create a scope of any kind -- it just limits the region where that particular replace / replacePP operates on. replace / replacePP's inside braces can still affect tokens outside those braces.

**Comment by qwertie** [comment]
Yeah, I will edit my comment to clarify that neither `replace` nor `define` create a scope. But you don't need extra nesting levels since you can write

    replace(A=>B, X=>Y) { ... }

instead of 

    replace(A=>B) { replace(X=>Y) { ... } }

**Comment by j4m3z0r** [comment]
Brilliant! That will make things much neater. The subtleties of replace and replacePP have turned out to be pretty pivotal for getting my project right. Hopefully these issues will serve as helpful documentation for the next person to attempt something similar. Thanks for the info.
