### ISSUE TITLE
Loyc.Syntax: FunctionCall arglist allowed values?

### ISSUE THREAD

**Issue by furesoft** [qwertie/ecsharp#95]
what are the valid values for arglist?

**Comment by qwertie** [comment]
The libraries contain no symbols called `FunctionCall` or `arglist`.

Loyc tree nodes ([LNode](http://ecsharp.net/doc/code/classLoyc_1_1Syntax_1_1LNode.html)), including call nodes, can have any other Loyc tree nodes as children, so all values are (structurally) valid.

**Comment by furesoft** [comment]
In the LNodeFactory is  a method called Fn
